#[derive(Debug, Clone, PartialEq)]
pub enum Token {

    Select,
    Distinct,
    From,
    Where,
    Insert,
    Into,
    Values,
    Update,
    Set,
    Delete,
    Create,
    Drop,
    Alter,
    Add,
    Rename,
    Column,
    Union,
    All,
    Table,
    Index,
    On,
    Primary,
    Key,
    Not,
    Null,
    Unique,
    If,
    Exists,
    And,
    Or,
    Order,
    By,
    Asc,
    Desc,
    Limit,
    Offset,
    Join,
    Inner,
    Left,
    Right,
    Group,
    Having,
    As,
    In,
    Like,
    Between,
    Is,
    Begin,
    Commit,
    Rollback,
    Serializable,
    Case,
    When,
    Then,
    Else,
    End,
    Cast,
    Returning,
    Conflict,
    Do,
    Nothing,
    Ilike,
    With,
    Recursive,
    Over,
    Partition,
    Rows,
    Range,
    Unbounded,
    Preceding,
    Following,
    Current,
    Row,
    Explain,
    Analyze,
    Nulls,
    First,
    Last,
    Intersect,
    Except,
    Show,
    Columns,
    Tables,
    Truncate,
    Default,
    Database,
    Use,
    Cascade,
    Restrict,
    Backup,
    Restore,
    Migrate,
    To,
    Lsn,

    Kv,
    Get,
    Scan,

    Doc,
    Find,

    Int,
    Float,
    Text,
    Bool,
    Bytes,
    Json,
    Timestamp,
    Varchar,
    Integer,
    Bigint,
    Smallint,
    Real,
    DoublePrecision,
    Numeric,
    Serial,
    Uuid,
    Date,
    Interval,
    Blob,

    HexBlob(Vec<u8>),

    IntLit(i64),
    FloatLit(f64),
    StringLit(String),
    BoolLit(bool),
    NullLit,

    Ident(String),

    Eq,
    Neq,
    Lt,
    Gt,
    Lte,
    Gte,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    DoubleColon,

    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Comma,
    Semicolon,
    Dot,
    DollarDot,
    Colon,

    Eof,
}

impl Token {
    pub fn is_keyword(s: &str) -> Option<Token> {
        match s.to_uppercase().as_str() {
            "SELECT" => Some(Token::Select),
            "DISTINCT" => Some(Token::Distinct),
            "FROM" => Some(Token::From),
            "WHERE" => Some(Token::Where),
            "INSERT" => Some(Token::Insert),
            "INTO" => Some(Token::Into),
            "VALUES" => Some(Token::Values),
            "UPDATE" => Some(Token::Update),
            "SET" => Some(Token::Set),
            "DELETE" => Some(Token::Delete),
            "CREATE" => Some(Token::Create),
            "DROP" => Some(Token::Drop),
            "ALTER" => Some(Token::Alter),
            "ADD" => Some(Token::Add),
            "RENAME" => Some(Token::Rename),
            "COLUMN" => Some(Token::Column),
            "UNION" => Some(Token::Union),
            "ALL" => Some(Token::All),
            "TABLE" => Some(Token::Table),
            "INDEX" => Some(Token::Index),
            "ON" => Some(Token::On),
            "PRIMARY" => Some(Token::Primary),
            "KEY" => Some(Token::Key),
            "NOT" => Some(Token::Not),
            "NULL" => Some(Token::NullLit),
            "UNIQUE" => Some(Token::Unique),
            "IF" => Some(Token::If),
            "EXISTS" => Some(Token::Exists),
            "AND" => Some(Token::And),
            "OR" => Some(Token::Or),
            "ORDER" => Some(Token::Order),
            "BY" => Some(Token::By),
            "ASC" => Some(Token::Asc),
            "DESC" => Some(Token::Desc),
            "LIMIT" => Some(Token::Limit),
            "OFFSET" => Some(Token::Offset),
            "JOIN" => Some(Token::Join),
            "INNER" => Some(Token::Inner),
            "LEFT" => Some(Token::Left),
            "RIGHT" => Some(Token::Right),
            "GROUP" => Some(Token::Group),
            "HAVING" => Some(Token::Having),
            "AS" => Some(Token::As),
            "IN" => Some(Token::In),
            "LIKE" => Some(Token::Like),
            "BETWEEN" => Some(Token::Between),
            "IS" => Some(Token::Is),
            "BEGIN" => Some(Token::Begin),
            "COMMIT" => Some(Token::Commit),
            "ROLLBACK" => Some(Token::Rollback),
            "SERIALIZABLE" => Some(Token::Serializable),
            "CASE" => Some(Token::Case),
            "WHEN" => Some(Token::When),
            "THEN" => Some(Token::Then),
            "ELSE" => Some(Token::Else),
            "END" => Some(Token::End),
            "CAST" => Some(Token::Cast),
            "RETURNING" => Some(Token::Returning),
            "CONFLICT" => Some(Token::Conflict),
            "DO" => Some(Token::Do),
            "NOTHING" => Some(Token::Nothing),
            "ILIKE" => Some(Token::Ilike),
            "WITH" => Some(Token::With),
            "RECURSIVE" => Some(Token::Recursive),
            "OVER" => Some(Token::Over),
            "PARTITION" => Some(Token::Partition),
            "ROWS" => Some(Token::Rows),
            "RANGE" => Some(Token::Range),
            "UNBOUNDED" => Some(Token::Unbounded),
            "PRECEDING" => Some(Token::Preceding),
            "FOLLOWING" => Some(Token::Following),
            "CURRENT" => Some(Token::Current),
            "ROW" => Some(Token::Row),
            "EXPLAIN" => Some(Token::Explain),
            "ANALYZE" => Some(Token::Analyze),
            "NULLS" => Some(Token::Nulls),
            "FIRST" => Some(Token::First),
            "LAST" => Some(Token::Last),
            "INTERSECT" => Some(Token::Intersect),
            "EXCEPT" => Some(Token::Except),
            "SHOW" => Some(Token::Show),
            "COLUMNS" => Some(Token::Columns),
            "TABLES" => Some(Token::Tables),
            "TRUNCATE" => Some(Token::Truncate),
            "DEFAULT" => Some(Token::Default),
            "DATABASE" => Some(Token::Database),
            "SCHEMA" => Some(Token::Database),
            "USE" => Some(Token::Use),
            "CASCADE" => Some(Token::Cascade),
            "RESTRICT" => Some(Token::Restrict),
            "BACKUP" => Some(Token::Backup),
            "RESTORE" => Some(Token::Restore),
            "MIGRATE" => Some(Token::Migrate),
            "TO" => Some(Token::To),
            "LSN" => Some(Token::Lsn),
            "KV" => Some(Token::Kv),
            "GET" => Some(Token::Get),
            "SCAN" => Some(Token::Scan),
            "DOC" => Some(Token::Doc),
            "FIND" => Some(Token::Find),
            "INT" => Some(Token::Int),
            "FLOAT" => Some(Token::Float),
            "TEXT" => Some(Token::Text),
            "BOOL" => Some(Token::Bool),
            "BYTES" => Some(Token::Bytes),
            "JSON" => Some(Token::Json),
            "TIMESTAMP" => Some(Token::Timestamp),
            "VARCHAR" => Some(Token::Varchar),
            "INTEGER" => Some(Token::Integer),
            "BIGINT" => Some(Token::Bigint),
            "SMALLINT" => Some(Token::Smallint),
            "REAL" => Some(Token::Real),
            "DOUBLE" => Some(Token::DoublePrecision),
            "NUMERIC" => Some(Token::Numeric),
            "DECIMAL" => Some(Token::Numeric),
            "SERIAL" => Some(Token::Serial),
            "UUID" => Some(Token::Uuid),
            "DATE" => Some(Token::Date),
            "INTERVAL" => Some(Token::Interval),
            "BLOB" => Some(Token::Blob),
            "TRUE" => Some(Token::BoolLit(true)),
            "FALSE" => Some(Token::BoolLit(false)),
            _ => None,
        }
    }
}
